### PR TITLE
Fixes Docker, gets z80 building again, md-echo-test builds with docker

### PR DESCRIPTION
**Pull request by dleslie**
I put some time in this week to get the Dockerfile for marsdev up and going.

The changes break it up into smaller chunks so that it can cache more effectively, along with setting permissions and such so that executing as an unprivileged user doesn't write files to the host as root.

All said and done, it appears that `md-echo-test` now compiles once again.

### CODE REVIEW

**Comment by dleslie** [comment]
ssg-mapper and stage9-sample examples still fail....

**Comment by dleslie** [comment]
This isn't quite ready for merging yet, I want to get those last two building.

**Comment by dleslie** [comment]
Well this is a pickle:

```/marsdev/mars/bin/rescomp res/resources.res res/resources.s
ResComp 3.1 - SGDK Resource Compiler - Copyright 2020 (Stephane Dallongeville)

Resource: PALETTE PAL_Tiny16 "tiny16.png" 2
--> executing plugin PALETTE...'PAL_Tiny16' raw size: 38 bytes
Resource: TILESET TS_Tiny16 "tiny16.png" 0
--> executing plugin TILESET...#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000400af24f21, pid=17, tid=0x0000004002d07700
#
# JRE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.275-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 293 C1 sgdk.tool.TypeUtil.unsign(B)I (6 bytes) @ 0x000000400af24f21 [0x000000400af24f20+0x1]
#
# Core dump written. Default location: /data/core or core.17
#
# An error report file with more information is saved as:
# /data/hs_err_pid17.log
Compiled method (c1)    9835  293       2       sgdk.tool.TypeUtil::unsign (6 bytes)
 total in heap  [0x000000400af24dd0,0x000000400af250a8] = 728
 relocation     [0x000000400af24ef8,0x000000400af24f20] = 40
 main code      [0x000000400af24f20,0x000000400af24fc0] = 160
 stub code      [0x000000400af24fc0,0x000000400af25050] = 144
 oops           [0x000000400af25050,0x000000400af25058] = 8
 metadata       [0x000000400af25058,0x000000400af25060] = 8
 scopes data    [0x000000400af25060,0x000000400af25070] = 16
 scopes pcs     [0x000000400af25070,0x000000400af250a0] = 48
 dependencies   [0x000000400af250a0,0x000000400af250a8] = 8
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

**Comment by dleslie** [comment]
@andwn have you seen rescomp segfault before?

**Comment by dleslie** [comment]
@andwn nevermind, disk error. Ah, raspberry pis...

Ok, so only ssfmapper doesn't compile now.

**Comment by dleslie** [comment]
Oh, stage9 too. My mistake

**Comment by andwn** [comment]
Hey, thanks for fixing that stuff. Haven't considered making a wrapper for rescomp like that but good idea. If you aren't already knee deep in ssf-mapper I can go fix it since I have to work on something else MD related over the weekend. It's just the function names for the interrupts changed in SGDK 1.60.

**Comment by dleslie** [comment]
Please do, I'm in the middle of making dinner for my family.

-------- Original Message --------

**Comment by andwn** [comment]
Ok ssfmapper example is working. The stage9 sample compiles but doesn't work properly still. I'm not sure if it's really worth fixing unless I decide to rewrite the defunct map editing tool it came from.

**Comment by andwn** [comment]
I don't know if I was supposed to merge that yet, but I added 2 commits to it that didn't show up on github. Figured it would be less confusing to just do it.

**Comment by dleslie** [comment]
All good, I would've asked to merge if it wasn't for the stage9 example.

**Pull request merged**
