### PR TITLE
Add Blastem emulator

### PR DESCRIPTION
**Pull request by tapule**
What do you think about adding Blastem to the toolchain?

### CODE REVIEW

**Comment by andwn** [comment]
I do use BlastEm most of the time and would be happy to add it to the toolchain. However I would prefer to compile from source rather than pulling the binary for a specific OS. Maybe the mercurial repo has tags for released versions like 0.6.2?

If not we could instead change the filename of the binary package based on OS. As messy as this looks it'll probably work

```
BLASTEM_BITS = 64
BLASTEM_VER  = 0.6.2
BLASTEM_EXT = tar.gz

UNAME=
ifeq ($(OS),Windows_NT) 
    UNAME := Windows
else
    UNAME := $(shell sh -c 'uname 2>/dev/null || echo Unknown')
endif

ifeq ($(UNAME), Windows)
    BLASTEM_BITS := win32
    BLASTEM_EXT := zip
endif
ifeq ($(UNAME), Darwin)
    BLASTEM_BITS := osx
endif
```

**Comment by tapule** [comment]
I agree with you, compiling from sources would be great but I think some libs like sdl were needed to compile. I will take a look on this ;)
Btw, thank you so much for this fantastic toolchain, it made me easy starting on md programming.

**Comment by dleslie** [comment]
Yes, source please, compiling from sources is preferable for those of us not on x86-64.

**Comment by dleslie** [comment]
Nevermind, blastem is x86-only; it includes significant x86 instructions. It'd be a fair amount of work to make it portable.

**Pull request closed without merging**
